runtime: go
api_version: go1
application: myappengineapp
version: 1



handlers:
- url: /
  script: _go_app

- url: /setdata
  script: _go_app

- url: /getdata
  script: _go_app 



- url: /static
  static_dir: static